#!/usr/bin/env bash
set -euo pipefail

project_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
if [[ -f "$project_dir/.env" ]]; then
  # This is the local file generated by prepare-local-env.sh.
  set -a
  source "$project_dir/.env"
  set +a
fi
: "${MERCHANT_DEMO_PASSWORD:?Generate .env with scripts/prepare-local-env.sh or export MERCHANT_DEMO_PASSWORD}"
for dependency in curl jq openssl; do
  command -v "$dependency" >/dev/null || { printf 'Missing dependency: %s\n' "$dependency" >&2; exit 1; }
done
base_url=${BASE_URL:-http://localhost:8080}
merchant=${MERCHANT_USERNAME:-demo-merchant}
account_id=${ACCOUNT_ID:-11111111-1111-1111-1111-111111111111}
run_id="demo-$(openssl rand -hex 8)"
work_dir=$(mktemp -d)
trap 'rm -rf "$work_dir"' EXIT

fail() { printf 'Demo failed: %s\n' "$*" >&2; exit 1; }
request() {
  local label=$1 method=$2 path=$3 expected=$4 key=${5:-} body=${6:-}
  local args=(--silent --show-error --connect-timeout 5 --max-time 20
    --user "$merchant:$MERCHANT_DEMO_PASSWORD"
    --request "$method" --dump-header "$work_dir/headers"
    --output "$work_dir/body" --write-out '%{http_code}')
  [[ -z "$key" ]] || args+=(--header "Idempotency-Key: $key")
  [[ -z "$body" ]] || args+=(--header 'Content-Type: application/json' --data "$body")
  local actual
  actual=$(curl "${args[@]}" "$base_url$path")
  [[ "$actual" == "$expected" ]] || { cat "$work_dir/body" >&2; fail "$label expected HTTP $expected, received $actual"; }
  printf 'PASS  %s (HTTP %s)\n' "$label" "$actual"
}

printf 'DecisionRail local operator demo: %s\n' "$base_url"
request 'health' GET /actuator/health 200
request 'read account' GET "/v1/accounts/$account_id" 200
starting_balance=$(jq -er '.balanceMinor' "$work_dir/body")
starting_held=$(jq -er '.heldMinor' "$work_dir/body")
starting_available=$(jq -er '.availableMinor' "$work_dir/body")
(( starting_available >= 3500 )) || fail 'demo needs at least 3500 minor units available'

payload=$(jq -cn --arg id "$account_id" '{accountId:$id,amountMinor:2500,currency:"CAD",country:"CA"}')
request 'authorize CAD 25.00' POST /v1/payments/authorizations 201 "$run_id-authorize" "$payload"
payment_id=$(jq -er '.id' "$work_dir/body")
jq -e '.status == "AUTHORIZED" and .decision.ruleSetVersion != null and .decision.reasons != null' "$work_dir/body" >/dev/null || fail 'authorization or versioned decision missing'
cp "$work_dir/body" "$work_dir/original"
request 'replay identical authorization' POST /v1/payments/authorizations 201 "$run_id-authorize" "$payload"
diff -q <(jq -S . "$work_dir/original") <(jq -S . "$work_dir/body") >/dev/null || fail 'idempotent replay changed the response'
awk 'tolower($0) ~ /^idempotency-replayed: true/ {found=1} END {exit !found}' "$work_dir/headers" || fail 'replay header missing'

changed_payload=$(jq -cn --arg id "$account_id" '{accountId:$id,amountMinor:2600,currency:"CAD",country:"CA"}')
request 'reject conflicting idempotency reuse' POST /v1/payments/authorizations 409 "$run_id-authorize" "$changed_payload"
request 'capture authorized payment' POST "/v1/payments/$payment_id/capture" 200 "$run_id-capture"
jq -e '.status == "CAPTURED"' "$work_dir/body" >/dev/null || fail 'capture status missing'
cp "$work_dir/body" "$work_dir/captured"
request 'replay capture' POST "/v1/payments/$payment_id/capture" 200 "$run_id-capture"
diff -q <(jq -S . "$work_dir/captured") <(jq -S . "$work_dir/body") >/dev/null || fail 'capture replay changed the response'
request 'read persisted capture journal' GET "/v1/payments/$payment_id/ledger" 200
jq -e 'length == 2 and (map(.journalId) | unique | length) == 1 and (map(.side) | sort) == ["CREDIT","DEBIT"] and all(.[]; .currency == "CAD" and .amountMinor == 2500)' "$work_dir/body" >/dev/null || fail 'capture journal is not a balanced CAD 2500 debit/credit pair'
jq . "$work_dir/body"
request 'read stored payment decision' GET "/v1/payments/$payment_id" 200
jq '{id,status,decision}' "$work_dir/body"

void_payload=$(jq -cn --arg id "$account_id" '{accountId:$id,amountMinor:1000,currency:"CAD",country:"CA"}')
request 'authorize a second payment' POST /v1/payments/authorizations 201 "$run_id-authorize-void" "$void_payload"
void_id=$(jq -er '.id' "$work_dir/body")
request 'void and release the second hold' POST "/v1/payments/$void_id/void" 200 "$run_id-void"
jq -e '.status == "VOIDED"' "$work_dir/body" >/dev/null || fail 'void status missing'
request 'read final account' GET "/v1/accounts/$account_id" 200
jq -e --argjson balance "$starting_balance" --argjson held "$starting_held" \
  '.balanceMinor == ($balance - 2500) and .heldMinor == $held and .availableMinor == (.balanceMinor - .heldMinor)' \
  "$work_dir/body" >/dev/null || fail 'account balances do not match capture and void results'
jq . "$work_dir/body"
printf '\nDemo passed. Captured CAD 25.00 of synthetic funds; the other hold was released.\n'
printf 'Each run uses new keys and consumes another CAD 25.00 of synthetic balance.\n'
